_wandb:
    value:
        cli_version: 0.23.1
        e:
            2bsrmxhu79bqony6mvpncxtaorrawl3f:
                codePath: d:\Projects\final_project\elliptic_model\train_graphsage.ipynb
                codePathLocal: train_graphsage.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2000381014016"
                        used: "1424448028672"
                email: orisin@post.bgu.ac.il
                executable: d:\Projects\final_project\.venv\Scripts\python.exe
                git:
                    commit: ac71ad990d6c9f7137b123b4c78111fddba62e42
                    remote: https://github.com/NehorayChalfon0166/final_project.git
                gpu: NVIDIA GeForce RTX 2080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2944
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080
                      uuid: GPU-e8f72c14-b206-0d4c-ac2f-dc846cbfaa30
                host: orimood-pc
                memory:
                    total: "68558614528"
                os: Windows-10-10.0.26200-SP0
                program: d:\Projects\final_project\elliptic_model\train_graphsage.ipynb
                python: CPython 3.10.7
                root: d:\Projects\final_project\elliptic_model
                startedAt: "2025-12-25T11:10:06.449589Z"
                writerId: 2bsrmxhu79bqony6mvpncxtaorrawl3f
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.7
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
data_dir:
    value: ../Elipticpp_Data
dropout:
    value: 0.5
epochs:
    value: 200
focal_gamma:
    value: 2
hidden_channels:
    value: 128
include_unknown:
    value: false
lr:
    value: 0.01
model_type:
    value: graphsage
num_layers:
    value: 3
patience:
    value: 20
run_name:
    value: graphsage_weighted_h128_l3_binary
smote_ratio:
    value: 0.5
strategy:
    value: weighted
time_step:
    value: null
use_wandb:
    value: true
wandb_entity:
    value: orisin-ben-gurion-university-of-the-negev
wandb_project:
    value: elliptic-fraud-detection
weight_decay:
    value: 0.0005
